# Generated by Django 4.2 on 2024-09-09 06:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shpos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Saleing_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=255)),
                ('discription', models.TextField(max_length=2500)),
                ('price', models.FloatField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shpos.category')),
                ('entry_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='meida/product/images')),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shss.saleing_product')),
            ],
        ),
    ]
