# Generated by Django 4.2 on 2024-09-09 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.FloatField()),
                ('sp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shss.saleing_product')),
            ],
        ),
    ]
