# Generated by Django 4.2 on 2024-09-12 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0003_alter_saleing_product_date_product_add_to_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add_to_card',
            name='qt',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
