# Generated by Django 4.2 on 2024-09-21 05:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0004_alter_product_add_to_card_qt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_add_to_card',
            name='qt',
            field=models.FloatField(blank=True, default=1, null=True),
        ),
        migrations.CreateModel(
            name='My_Check_Out',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qt', models.FloatField()),
                ('address', models.TextField(verbose_name=500)),
                ('payment_method', models.CharField(max_length=255)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('order_id', models.CharField(max_length=12)),
                ('status', models.BooleanField(default=False)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shss.saleing_product')),
            ],
        ),
    ]
