# Generated by Django 4.2 on 2024-09-21 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0005_alter_product_add_to_card_qt_my_check_out'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_check_out',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
