# Generated by Django 4.2 on 2024-09-25 03:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0008_web_category_alter_my_check_out_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('amount', models.FloatField()),
                ('active', models.BooleanField(default=True)),
                ('sp', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='shss.saleing_product')),
            ],
        ),
    ]
