# Generated by Django 4.2 on 2024-09-25 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0009_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleing_product',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
