# Generated by Django 4.2 on 2024-09-28 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0011_my_check_out_phone_number_alter_my_check_out_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_check_out',
            name='accept',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='my_check_out',
            name='order_id',
            field=models.CharField(max_length=40),
        ),
    ]
