# Generated by Django 4.2 on 2024-09-28 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0012_my_check_out_accept_alter_my_check_out_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_check_out',
            name='companyname',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='my_check_out',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
