# Generated by Django 4.2 on 2024-09-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0013_my_check_out_companyname_my_check_out_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='my_check_out',
            name='deny',
            field=models.BooleanField(default=False),
        ),
    ]
