# Generated by Django 4.2 on 2024-10-03 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shss', '0014_my_check_out_deny'),
    ]

    operations = [
        migrations.AddField(
            model_name='product_add_to_card',
            name='amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
